# -*- coding: utf-8 -*-
"""Train GPT in PyTorch and Lighning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gApQGXmqdJ7oiZmRYfxzIMmMOyK0xcOL
"""

!pip install torch
!pip install lightning

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import lightning as L

# Hyperparameters
batch_size = 64
context_length = 256
max_iters = 5000
learning_rate = 3e-4
eval_interval = 500
eval_iters = 200
n_embed = 384
n_layers = 6
n_heads = 6
dropout = 0.2
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(32)

# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

with open("input.txt", 'r', encoding='utf-8') as f:
    text = f.read()

print(text[:1000])

chars = sorted(list(set(text)))
vocab_size = len(chars)

idx_to_char = {idx: char for idx, char in enumerate(chars) }
char_to_idx = {char: idx for idx, char in enumerate(chars) }

encode = lambda x: [char_to_idx[i] for i in x]
decode = lambda x: ''.join([idx_to_char[i] for i in x])

# print((encode(text[:1000])))

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9 * len(data))

train_data = data[:n]
val_data = data[n:]

x = train_data[: context_length]
y = train_data[1:context_length + 1]

# for i in range(context_length):
#     context = x[:i+1]
#     target = y[i]
#     print(f'for context ', context, '- target ',target)

class ShakespeareDataset(L.LightningDataModule):
    def __init__(self, train_data, val_data, context_length, batch_size, device):
        super().__init__()
        self.train_data = train_data
        self.val_data = val_data
        self.context_length = context_length
        self.batch_size = batch_size
        self.device = device

    def train_dataloader(self):
        return DataLoader(self.train_data, batch_size=self.batch_size, collate_fn=self.get_batch)

    def val_dataloader(self):
        return DataLoader(self.val_data, batch_size=self.batch_size, collate_fn=self.get_batch)

    def get_batch(self, data):
        """Function to get a batch of data with text and labels. Acts like a torch DataLoader"""
        idx = torch.randint(low = 0, high = len(data) - self.context_length, size = (self.batch_size,))
        x = torch.stack([data[i : i + self.context_length] for i in idx])
        y = torch.stack([data[i+1: i+ self.context_length + 1] for i in idx])
        x, y = x.to(device), y.to(device)
        return x, y

class Head(nn.Module):
    """Single head of Attention"""
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embed, head_size, bias = False)
        self.query = nn.Linear(n_embed, head_size, bias = False)
        self.value = nn.Linear(n_embed, head_size, bias = False)
        self.register_buffer('tril', torch.tril(torch.ones(context_length, context_length)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        key = self.key(x) # (B,T,C); C/4 because we are keeping head size same as n_embed (for now)
        query = self.query(x) # (B,T,C)
        value = self.value(x) # (B,T,C)

        weights = query @ key.transpose(-2,-1) * C**-0.5 # # (B,T,C) * # (B,C,T) = (B,T,T)
        weights = weights.masked_fill(self.tril[:T,:T] == 0, float('-inf'))
        weights = F.softmax(weights, dim = -1) # (B,T,T)
        weights = self.dropout(weights)
        out = weights @ value # (W, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """Class for Multi-head attention"""
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.num_heads = num_heads
        self.head_size = head_size
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.projection = nn.Linear(n_embed, n_embed)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim = -1)
        out = self.projection(out)
        out = self.dropout(out)
        return out

class FeedForward(nn.Module):
    """Feedforward block to be used after attention"""
    def __init__(self, n_embed):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(n_embed, 4 * n_embed),
                                 nn.ReLU(),
                                 nn.Linear(4 * n_embed, n_embed),
                                 nn.Dropout(dropout))

    def forward(self, x):
        out = self.net(x)
        return out

class Block(nn.Module):
    """A block of Multihead attention with feedforward layers, along with residual connections"""
    def __init__(self, n_embed, n_heads):
        super().__init__()
        self.n_embed = n_embed
        self.n_heads = n_heads
        self.head_size = n_embed//n_heads
        self.self_attention = MultiHeadAttention(self.n_heads, self.head_size)
        self.ffwd = FeedForward(self.n_embed)
        self.ln1 = nn.LayerNorm(n_embed)
        self.ln2 = nn.LayerNorm(n_embed)

    def forward(self, x):
        x = x + self.self_attention(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class BiGramModel(L.LightningModule):
    """Putting it all together"""
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embed)
        self.pos_embedding_table = nn.Embedding(context_length, n_embed)
        self.attention_ffwd_blocks = nn.Sequential(*[Block(n_embed, n_heads=n_heads) for _ in range(n_layers)])
        self.layernorm = nn.LayerNorm(n_embed)
        self.lm_head = nn.Linear(n_embed, vocab_size)

    def forward(self, idx, target = None):
        B, T = idx.shape
        token_emb = self.token_embedding_table(idx) # (B, T, n_embed);;   x: (B, T)
        pos_emb = self.pos_embedding_table(torch.arange(T, device = device)) # (T, n_embed)
        x = token_emb + pos_emb # (B, T, n_embed)
        x = self.attention_ffwd_blocks(x)
        x = self.layernorm(x)
        logits = self.lm_head(x) # (B, T, vocab_size)

        if target is None:
            return logits, None

        else: # Else block for generation ie target isn't available
            B, T, C = logits.shape # original shape; C is the embedding size
            logits = logits.view(B*T, C) # Reshaping because torch's cross entropy loss function expects tensors in a certain format;
            target = target.view(B * T) # reshaping due to the reason above
            loss = F.cross_entropy(logits, target)
            return logits, loss


    def training_step(self, batch, batch_idx=None):

        idx, target = batch
        B, T = idx.shape
        token_emb = self.token_embedding_table(idx) # (B, T, n_embed);;   x: (B, T)
        pos_emb = self.pos_embedding_table(torch.arange(T, device = device)) # (T, n_embed)
        x = token_emb + pos_emb # (B, T, n_embed)
        x = self.attention_ffwd_blocks(x)
        x = self.layernorm(x)
        logits = self.lm_head(x) # (B, T, vocab_size)

        B, T, C = logits.shape # original shape; C is the embedding size
        logits = logits.view(B*T, C) # Reshaping because torch's cross entropy loss function expects tensors in a certain format;
        target = target.view(B * T) # reshaping due to the reason above
        loss = F.cross_entropy(logits, target)
        return loss

    def test_step(self, batch, batch_idx=None):
        # this is the test loop
        idx, target = batch
        token_emb = self.token_embedding_table(idx) # (B, T, n_embed);;   x: (B, T)
        pos_emb = self.pos_embedding_table(torch.arange(T, device = device)) # (T, n_embed)
        x = token_emb + pos_emb # (B, T, n_embed)
        x = self.attention_ffwd_blocks(x)
        x = self.layernorm(x)
        logits = self.lm_head(x) # (B, T, vocab_size)

        B, T, C = logits.shape # original shape; C is the embedding size
        logits = logits.view(B*T, C) # Reshaping because torch's cross entropy loss function expects tensors in a certain format;
        target = target.view(B * T) # reshaping due to the reason above
        loss = F.cross_entropy(logits, target)
        self.log("test_loss", test_loss)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=learning_rate)
        return optimizer

    def generate(self, x, max_new_tokens = 100):
        # x is of shape (B, T) array of indices in the current context
        for i in range(max_new_tokens):
            x_cond = x[..., -context_length:] # Because if the input is more than context length, the attention won't work
            logits, loss = self(x_cond  )
            logits = logits[:, -1, :] # becomes (B, C)
            probs = F.softmax(logits, dim = 1) # (B, C)
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            x = torch.cat((x, idx_next), dim = 1) # (B, T+1) as we concat B, T with B, 1 on axis = 1

        return x

def get_batch(data):
    """Function to get a batch of data with text and labels. Acts like a torch DataLoader"""
    idx = torch.randint(low = 0, high = len(data) - context_length, size = (batch_size,))
    x = torch.stack([data[i : i + context_length] for i in idx])
    y = torch.stack([data[i+1: i+ context_length + 1] for i in idx])
    train_dataset = torch.utils.data.TensorDataset(x, y)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size,
                                             shuffle=True)
    return train_loader

model = BiGramModel()

trainer = L.Trainer(max_epochs=1000)

trainer.fit(model, train_dataloaders= get_batch(train_data))